FROM node:18-alpine

RUN mkdir -p /var/www/super-admin
WORKDIR /var/www/super-admin
ADD . /var/www/super-admin

RUN npm install -g pnpm

RUN pnpm config set network-timeout 600000 -g

RUN pnpm install 

RUN pnpm nx reset

RUN pnpm exec nx build super-admin

CMD ["node", "./dist/apps/super-admin/main.js"]
