FROM node:18-alpine

RUN mkdir -p /var/www/air-services
WORKDIR /var/www/air-services
ADD . /var/www/air-services

RUN npm config set network-timeout 600000 -g

RUN npm install

RUN npm exec nx build air-services

CMD ["node", "./dist/apps/air-services/main.js"]
