FROM node:18-alpine

RUN mkdir -p /var/www/gateway
WORKDIR /var/www/gateway
ADD . /var/www/gateway

RUN npm config set network-timeout 600000 -g

RUN npm install

RUN npm exec nx build gateway

CMD ["node", "./dist/apps/gateway/main.js"]
