FROM node:18-alpine

RUN mkdir -p /var/www/sales
WORKDIR /var/www/sales
ADD . /var/www/sales

RUN npm config set network-timeout 600000 -g

RUN npm install

RUN npm exec nx build sales

CMD ["node", "./dist/apps/sales/main.js"]
