FROM node:18-alpine

RUN mkdir -p /var/www/org-admin
WORKDIR /var/www/org-admin
ADD . /var/www/org-admin

RUN npm config set network-timeout 600000 -g

RUN npm install

RUN npm exec nx build org-admin

CMD ["node", "./dist/apps/org-admin/main.js"]
