FROM node:18-alpine

RUN mkdir -p /var/www/operations
WORKDIR /var/www/operations
ADD . /var/www/operations

RUN npm config set network-timeout 600000 -g

RUN npm install

RUN npm exec nx build operations

CMD ["node", "./dist/apps/operations/main.js"]
