FROM node:18-alpine

RUN mkdir -p /var/www/super-admin
WORKDIR /var/www/super-admin
ADD . /var/www/super-admin

RUN npm config set network-timeout 600000 -g

RUN npm install

RUN npm exec nx build super-admin

CMD ["node", "./dist/apps/super-admin/main.js"]
