FROM node:18-alpine

RUN mkdir -p /var/www/marketing
WORKDIR /var/www/marketing
ADD . /var/www/marketing

RUN npm install -g pnpm

RUN pnpm config set network-timeout 600000 -g

RUN pnpm install --

RUN pnpm nx reset

RUN pnpm exec nx build marketing

CMD ["node", "./dist/apps/marketing/main.js"]
