FROM node:18-alpine

RUN mkdir -p /var/www/user-account
WORKDIR /var/www/user-account
ADD . /var/www/user-account

RUN npm install -g pnpm

RUN pnpm config set network-timeout 600000 -g

RUN pnpm install 

RUN pnpm nx reset

RUN pnpm exec nx build user-account

CMD ["node", "./dist/apps/user-account/main.js"]
