FROM node:18-alpine

RUN mkdir -p /var/www/cron
WORKDIR /var/www/cron
ADD . /var/www/cron

RUN npm config set fetch-retry-maxtimeout 600000 -g

RUN npm install

RUN npm exec nx build cron

CMD ["node", "./dist/apps/cron/main.js"]
