FROM node:18-alpine

RUN mkdir -p /var/www/operations
WORKDIR /var/www/operations
ADD . /var/www/operations

RUN npm install -g pnpm

RUN pnpm config set network-timeout 600000 -g

RUN pnpm install 

RUN pnpm nx reset

RUN pnpm exec nx build operations

CMD ["node", "./dist/apps/operations/main.js"]
