FROM node:18-alpine

RUN mkdir -p /var/www/common-feature
WORKDIR /var/www/common-feature
ADD . /var/www/common-feature

RUN npm config set fetch-retry-maxtimeout 600000 -g

RUN npm install

RUN npm exec nx build common-feature

CMD ["node", "./dist/apps/common-feature/main.js"]
