FROM node:18-alpine

RUN mkdir -p /var/www/loyalty-program
WORKDIR /var/www/loyalty-program
ADD . /var/www/loyalty-program

RUN npm config set network-timeout 600000 -g

RUN npm install

RUN npm exec nx build loyalty-program

CMD ["node", "./dist/apps/loyalty-program/main.js"]
