FROM node:18-alpine

RUN mkdir -p /var/www/air-services
WORKDIR /var/www/air-services
ADD . /var/www/air-services

RUN npm install -g pnpm

RUN pnpm config set network-timeout 600000 -g

RUN pnpm install

RUN pnpm exec nx build air-services

CMD ["node", "./dist/apps/air-services/main.js"]
