FROM node:18-alpine

RUN mkdir -p /var/www/common-feature
WORKDIR /var/www/common-feature
ADD . /var/www/common-feature

RUN npm install -g pnpm

RUN pnpm config set network-timeout 600000 -g

RUN pnpm install --force

RUN pnpm nx reset

RUN pnpm exec nx build common-feature

CMD ["node", "./dist/apps/common-feature/main.js"]
