export * from './add-news-or-event.dto';
export * from './add-news-or-event-response.dto';
export * from './edit-news-or-event.dto';
export * from './edit-news-or-event-response.dto';
export * from './get-news-or-event-repsone.dto';
export * from './get-news-or-events.dto';
export * from './get-news-and-events-response.dto';
export * from './delete-news-or-events.dto';
export * from './delete-new-or-event-response.dto';
