export const CONTROLLERS = {
  EXAMPLE: 'example',
  AUTHENTICATION: 'auth',
  ROLE: 'role',
  USER: 'user',
  PLAN: 'plan',
  BILLING: 'billing',
  ORGANIZATION: 'organization',
  ORGANIZATION_COMPANY_ACCOUNT: 'org-company-account',
  TASK: 'task',
  TASK_MANAGEMENT: 'task-management',
  SUPER_ADMIN: 'super-admin',
  SETTINGS: {
    JOBS: 'jobs',
    FAQS: 'faqs',
  },
  PRODUCTS: 'products',
  TICKET: 'ticket',
  ASSETS: 'assets',
  PRODUCT_FEATURES: 'product-features',
  EXPENSE: 'expense',
  CONTRACT: 'contract',
  ORGANIZATION_PLAN: 'organization-plan',
  AIR_SERVICES: 'air-services',

  NEWS_AND_EVENTS: 'news-and-events',
  PAYMENTS: 'payments',
  LOGS: 'requests-log',
  QUICK_LINKS: 'quick-links',
  INVOICES: 'invoices',
  ORG_ADMIN: {
    INVOICES: 'org-admin/invoices',
    SUBSCRIPTIONS: 'org-admin/subscriptions',
  },
  CONTACT: 'contact',
  PRODUCT_CATEGORIES: 'product-categories',
};
