export const MODEL = {
  EXAMPLE: 'Example',
  ASSETS: 'Asset',
  TICKET: 'Ticket',
  JOBS: 'Jobs',
  FAQS: 'Faqs',
  PLAN_TYPE: 'PlanType',
  PRODUCT: 'Product',
  PLAN: 'Plan',
  PLAN_PRODUCT: 'PlanProduct',
  MODULE: 'Module',
  MODULE_PERMISSION: 'ModulePermission',
  PLAN_PRODUCT_MODULE: 'PlanProductModule',
  FEATURE: 'Feature',
  PERMISSION: 'Permission',
};
