export const MODEL = {
  EXAMPLE: 'Example',
  SUPER_ADMIN: 'SUPER_ADMIN',
  INVENTORY: 'Inventory',
  TICKET: 'Ticket',
  ORGANIZATION_PLAN: 'OrganizationPlan',
  TASK: 'Task',
  JOBS: 'Jobs',
  FAQS: 'Faqs',
  PLAN_TYPE: 'plantypes',
  PRODUCT: 'Product',
  PLAN: 'Plan',
  PLAN_PRODUCT: 'PlanProduct',
  MODULE: 'Module',
  MODULE_PERMISSION: 'ModulePermission',
  PLAN_PRODUCT_MODULE: 'PlanProductModule',
  FEATURE: 'Feature',
  PERMISSION: 'Permission',
};
