export const MODEL = {
  EXAMPLE: 'Example',
  SUPER_ADMIN: 'SUPER_ADMIN',
  INVENTORY: 'Inventory',
  TICKET: 'Ticket',
  EXPENSE: 'Expense',
  CHILD_TICKET: 'ChildTicket',
  ORGANIZATION_PLAN: 'OrganizationPlan',
  ORGANIZATION: 'Organization',
  ORGANIZATION_COMPANY_ACCOUNT: 'OrganizationCompanyAccount',
  INVOICE: 'Invoice',
  TASK: 'Task',
  JOBS: 'Jobs',
  FAQS: 'Faqs',
  User: 'User',
  PLAN_TYPE: 'plantypes',
  PRODUCT: 'Product',
  PLAN_PRODUCT_FEATURE: 'planproductfeatures',
  PLAN_PRODUCT_MODULE_PERMISSION: 'planproductmodulepermissions',
  PLAN: 'Plan',
  MODULE: 'Module',
  MODULE_PERMISSION: 'ModulePermission',
  FEATURE: 'Feature',
  PERMISSION: 'Permission',
};
