export enum SERVICES {
  LOYALTY_PROGRAM = 'LOYALTY_PROGRAM_SERVICE',
  MARKETING = 'MARKETING_SERVICE',
  OPERATIONS = 'OPERATIONS_SERVICE',
  ORG_ADMIN = 'ORG_ADMIN_SERVICE',
  SALES = 'SALES_SERVICE',
  AIR_SERVICES = 'AIR_SERVICES_SERVICE',
  CRON = 'CRON_SERVICE',
  SUPER_ADMIN = 'SUPER_ADMIN_SERVICE',
  COMMON_FEATURE = 'COMMON_FEATURE_SERVICE',
  USER = 'USER_SERVICE',
}
