export const API_TAGS = {
  EXAMPLE: 'Example',
  AUTHENTICATION: 'Authentication',
  ORGANIZATION: 'Organization',
  ORGANIZATION_COMPANY_ACCOUNT: 'Organization Company Account',
  TASK: 'Task',
  SUPER_ADMIN: 'Super Admin',
  SETTINGS: 'Settings',
  TICKETS: 'Tickets',
  ASSETS: 'Assets',
  EXPENSE: 'Expense',
  BILLING_INVOICES: 'Billing & Invoices',
  PRODUCTS: 'Products',
  PAYMENTS: 'Payments',
};
