export const API_TAGS = {
  EXAMPLE: 'Example',
  AUTHENTICATION: 'Authentication',
  ROLE: 'Role',
  USER: 'User',
  PLAN: 'Plan',
  ORGANIZATION: 'Organization',
  ORGANIZATION_COMPANY_ACCOUNT: 'Organization Company Account',
  TASK: 'Task',
  TASK_MANAGEMENT: 'Task Management',
  WORK_LOAD_MANAGEMENT: 'Work Load Management',
  SUPER_ADMIN: 'Super Admin',
  SETTINGS: 'Settings',
  TICKETS: 'Tickets',
  ASSETS: 'Assets',
  EXPENSE: 'Expense',
  CONTRACT: 'Contract',
  BILLING_INVOICES: 'Billing & Invoices',
  PRODUCTS: 'Products',
  PRODUCT_FEATURES: 'Product Features',
  AIR_SERVICES_DASHBOARD: 'Air Services Dashboard',
  NEWS_AND_EVENTS: 'News and Events',
  REPORTS_WIDGETS: 'Reports',
  PAYMENTS: 'Payments',
  DOCUMENTS: 'Documents',

  LOGS: 'Requests log',
  QUICK_LINKS: 'Quick Links',
  INVOICES: 'Invoices',
  CONTACT: 'Contact',
  CONTACT_NOTE: 'Contact Note',
  CONTACT_CALL: 'Contact Call',
  CONTACT_MEETING: 'Contact Meeting',
  CONTACT_STATUS: 'contact-status',
  PRODUCT_CATEGORIES: 'Product Categories',
  LIFECYCLE_STAGES: 'Lifecycle Stages',
  DEAL_PIPELINE: 'Deal pipeline',
  SALES_PRODUCT: 'Sales product',
  ATTACHMENT: 'Attachment',
  ACTIVITY_LOGS: 'Activity Logs',
  ARTICLES: 'Articles',
  DEALS: 'Deals',
  DEAL_NOTE: 'Deal notes',
};
