import { Module } from '@nestjs/common';
import { ConfigModule, ConfigService } from '@nestjs/config';
import { MongooseModule } from '@nestjs/mongoose';
import { S3 } from '@aws-sdk/client-s3';
import { DbModels } from '../src/model.provider';
import {
  AdminRoleRepository,
  AssetsSoftwareRepository,
  ContactRepository,
  ContactStateRepository,
  ContractRepository,
  ExpenseRepository,
  FaqRepository,
  FeatureRepository,
  FileRepository,
  FolderRepository,
  InventoryRepository,
  InvoiceRepository,
  JobRepository,
  LifecycleStagesRepository,
  ModuleRepository,
  NewsAndEventRepository,
  // OrganizationCompanyAccountRepository,
  OrganizationPlanRepository,
  OrganizationRepository,
  PaymentRepository,
  PermissionRepository,
  PlanProductFeatureRepository,
  PlanProductModulePermissionRepository,
  PlanRepository,
  PlanTypeRepository,
  ProductCategoriesRepository,
  ProductFeaturesRepository,
  ProductsRepository,
  PurchaseRepository,
  QuickLinksRepository,
  RequestLogRepository,
  TaskActivityRepository,
  TaskManagementRepository,
  TaskRepository,
  TicketRepository,
  UserAccountsRepository,
  UserORepository,
  ContactNoteRepository,
  UserRepository,
  AttachmentAirRepository,
  ContactCallRepository,
} from '../src/repositories/index';
import { MongooseConfig } from './config/mongo.config';
import { SharedService } from './shared.service';
import { DownloadService, S3Service } from './services';
@Module({
  imports: [
    ConfigModule.forRoot(),
    MongooseModule.forRootAsync({
      useClass: MongooseConfig,
    }),
    MongooseModule.forFeature(DbModels),
  ],
  providers: [
    SharedService,
    TicketRepository,
    InventoryRepository,
    PurchaseRepository,
    TaskRepository,
    ProductsRepository,
    PlanRepository,
    PlanProductFeatureRepository,
    PlanProductModulePermissionRepository,
    NewsAndEventRepository,
    InvoiceRepository,
    OrganizationPlanRepository,
    JobRepository,
    FaqRepository,
    PaymentRepository,
    UserAccountsRepository,
    NewsAndEventRepository,
    InvoiceRepository,
    OrganizationPlanRepository,
    ProductFeaturesRepository,
    OrganizationRepository,
    ExpenseRepository,
    QuickLinksRepository,
    UserRepository,
    AdminRoleRepository,
    AssetsSoftwareRepository,
    FeatureRepository,
    // ModuleRepository,
    // PermissionRepository,
    UserORepository,
    TaskManagementRepository,
    UserORepository,
    ContactRepository,
    PlanTypeRepository,
    RequestLogRepository,
    TaskActivityRepository,
    ContactNoteRepository,
    UserORepository,
    FolderRepository,
    FileRepository,
    ProductCategoriesRepository,
    RequestLogRepository,
    // OrganizationCompanyAccountRepository,
    ContactStateRepository,
    ContractRepository,
    AttachmentAirRepository,
    ContactCallRepository,
    LifecycleStagesRepository,
    {
      provide: 'S3',
      useFactory: (config: ConfigService) =>
        new S3({
          region: config.get('S3_REGION'),
          credentials: {
            accessKeyId: config.get('S3_AWS_ACCESS_KEY'),
            secretAccessKey: config.get('S3_AWS_SECRET_KEY'),
          },
        }),
      inject: [ConfigService],
    },
    S3Service,
    DownloadService,
  ],
  exports: [
    SharedService,
    MongooseModule.forFeature(DbModels),
    TicketRepository,
    InventoryRepository,
    PurchaseRepository,
    TaskRepository,
    ProductsRepository,
    PlanRepository,
    PlanProductFeatureRepository,
    PlanProductModulePermissionRepository,
    NewsAndEventRepository,
    InvoiceRepository,
    OrganizationPlanRepository,
    JobRepository,
    FaqRepository,
    PaymentRepository,
    UserAccountsRepository,
    NewsAndEventRepository,
    InvoiceRepository,
    OrganizationPlanRepository,
    ProductFeaturesRepository,
    OrganizationRepository,
    // OrganizationCompanyAccountRepository,
    ExpenseRepository,
    QuickLinksRepository,
    UserRepository,
    AdminRoleRepository,
    AssetsSoftwareRepository,
    FeatureRepository,
    // ModuleRepository,
    // PermissionRepository,
    UserORepository,
    TaskManagementRepository,
    UserORepository,
    ContactRepository,
    PlanTypeRepository,
    RequestLogRepository,
    TaskActivityRepository,
    ContactNoteRepository,
    UserORepository,
    FolderRepository,
    FileRepository,
    ProductCategoriesRepository,
    RequestLogRepository,
    ContractRepository,
    S3Service,
    ContractRepository,
    AttachmentAirRepository,
    DownloadService,
    ContactStateRepository,
    ContactCallRepository,
    LifecycleStagesRepository,
  ],
})
export class SharedModule {}
